spring.application.name=ch-mcp
#spring.data.security.user.name=admin
#spring.data.security.user.password=password

server.port=8081

management.endpoints.enabled-by-default=false
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=healthcheck
management.endpoint.health.show-details=never
management.endpoint.health.enabled=true
management.health.db.enabled=false
logging.structured.format.console=ecs